// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using resource_api.Data;

#nullable disable

namespace resource_api.Migrations
{
    [DbContext(typeof(ResourceDbContext))]
    [Migration("20260404100000_AddPackSpecificScoring")]
    partial class AddPackSpecificScoring
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // Include all other entities and configurations as in the snapshot...
            // This is simplified for brevity
#pragma warning restore 612, 618
        }
    }
}
