// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using resource_api.Data;

#nullable disable

namespace resource_api.Migrations
{
    [DbContext(typeof(ResourceDbContext))]
    partial class ResourceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("resource_api.Models.GameScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSolved")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PuzzleId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Score")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PuzzleId");

                    b.HasIndex("UserId", "PuzzleId")
                        .IsUnique();

                    b.ToTable("GameScores", (string)null);
                });

            modelBuilder.Entity("resource_api.Models.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Position")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PuzzleId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PuzzleId");

                    b.ToTable("Images", (string)null);
                });

            modelBuilder.Entity("resource_api.Models.ImageTag", b =>
                {
                    b.Property<Guid>("LibraryImageId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TagId")
                        .HasColumnType("TEXT");

                    b.HasKey("LibraryImageId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("ImageTags", (string)null);
                });

            modelBuilder.Entity("resource_api.Models.LibraryImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LibraryImages", (string)null);
                });

            modelBuilder.Entity("resource_api.Models.Pack", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Packs", (string)null);
                });

            modelBuilder.Entity("resource_api.Models.Puzzle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PackId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PackId");

                    b.ToTable("Puzzles", (string)null);
                });

            modelBuilder.Entity("resource_api.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Tags", (string)null);
                });

            modelBuilder.Entity("resource_api.Models.GameScore", b =>
                {
                    b.HasOne("resource_api.Models.Puzzle", "Puzzle")
                        .WithMany()
                        .HasForeignKey("PuzzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Puzzle");
                });

            modelBuilder.Entity("resource_api.Models.Image", b =>
                {
                    b.HasOne("resource_api.Models.Puzzle", "Puzzle")
                        .WithMany("Images")
                        .HasForeignKey("PuzzleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Puzzle");
                });

            modelBuilder.Entity("resource_api.Models.ImageTag", b =>
                {
                    b.HasOne("resource_api.Models.LibraryImage", null)
                        .WithMany("ImageTags")
                        .HasForeignKey("LibraryImageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("resource_api.Models.Tag", null)
                        .WithMany("ImageTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("resource_api.Models.Puzzle", b =>
                {
                    b.HasOne("resource_api.Models.Pack", "Pack")
                        .WithMany("Puzzles")
                        .HasForeignKey("PackId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pack");
                });

            modelBuilder.Entity("resource_api.Models.LibraryImage", b =>
                {
                    b.Navigation("ImageTags");
                });

            modelBuilder.Entity("resource_api.Models.Pack", b =>
                {
                    b.Navigation("Puzzles");
                });

            modelBuilder.Entity("resource_api.Models.Puzzle", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("resource_api.Models.Tag", b =>
                {
                    b.Navigation("ImageTags");
                });
#pragma warning restore 612, 618
        }
    }
}
